### PR TITLE
RoR Capstone project: - JourneyCash App 🌟

### PR DESCRIPTION
**Pull request by jicamargo**
## RoR Capstone project: - JourneyCash App 🌟

# NOTE:

**This PR has been "canceled" and changed to another new branch called: budget-app with a PR 
to merge budget-app -> develop.**

👩‍💻👨‍💻 Thank you! 🚀🌈💎

### CODE REVIEW

**Review by elisha2kyakpo1 — CHANGES_REQUESTED** [review]
Hi 👋 @jicamargo, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has a wrong GitHub workflow. You should create a feature branch from the development branch, you will request to merge into the development branch.


gitflow


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by jicamargo** [comment]
Dear @elisha2kyakpo1 
Thank you very much for your review and comments. 
I kindly tell you that it could be an error, since I developed the entire project using gitflow and since it is a capstone project, I am requesting the latest revision from the develop branch to the main one.

**Comment by KDlamini** [comment]
## Status: Invalid 🔴 

### Hi @jicamargo  🙋‍♀️,  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request
 
You have submitted a project, that does not follow the project guidelines for submitting solo capstone projects. For this milestone the project submission mode should follow Gitflow.

Gitflow submission mode means your PR should be merging a `feature branch` to the `dev` branch. ***This is part of the project requirements, therefore, this pull request cannot be reviewed until a new feature branch is submitted.***

Working on solo projects can be done in two ways:

1. You can work on a single feature branch, and request a review with a PR that compares that feature branch with the development branch (merge feature branch into dev).
2. Alternatively, you can work on multiple feature branches, merge these branches into one feature branch that consolidates all the changes, and then create a PR for review that compares this branch to the development branch.

Unfortunately, to implement this change you will have to close this branch and create a new feature branch and submit a new review request comparing the new feature branch to the dev branch.

<hr>

## Solution Suggestions [OPTIONAL]
Note: This is just a suggestion, you are not obligated to implement it if it doesn't work for you. You are more than welcome to find your own solution.

`**OPTIONAL suggestion 1**`: The simplest way to create a new feature branch and still keep your commit history is to **(1)** rename the dev branch to a feature branch name like ***budget-app*** on GitHub, **(2)** Switch to the main branch locally and pull the changes, **(3)** Delete the dev branch locally, **(4)** Create a new dev branch from main and push it, **(5)** Create a new pull request merging the renamed branch to the new dev branch.

This way you will be able to merge the new renamed feature branch to the new dev branch and still keep your entire commit history.


`**OPTIONAL suggestion 2**`:
Step 1: From the `dev` branch, create a new feature branch called `budget-app` or any branch name of your choice. This will make sure that ALL the commits that are in the `dev` branch exist in the new branch.

However, our feature branch is currently up to date with the `dev` branch therefore there are no new changes on the new feature branch to compare to the `dev` in order to create a new pull request for a merge. Let's fix that.

Step 2: Undo the `dev` branch commits with `git reset` to make sure that the `dev` branch is behind the new feature branch with commits so that there are new changes to compare from the feature branch branch to the `dev`. Essentially you are just undoing the dev changes so you can merge them again from the feature branch. Remember all your changes are now shipped to the new feature branch therefore you are not going to lose your work.


Step 3: Note that `git reset` requires you to specify the number of commits you want to undo.

- The quickest way to achieve this is the run `git rev-list --all --count`. This will return the number of all commits merged to the `dev` branch. Example if the commit count is 31, then run `git log -n 30 --pretty=oneline` and copy the commit ID of the commit message at the very bottom of the list (the 30th commit), the ID looks like this "503038db18c2f387c3f34cac88f5731018ee4c86". Then run `git reset --hard 503038db18c2f387c3f34cac88f5731018ee4c86`, remember to use your commit ID. The reason we not are resetting 30 instead of all 31 commits is because we must leave at least one commit on the `dev`. Then run `git push -f`, `-f` will force the update. We will  now be able to merge your whole commit history form the feature branch to the dev again.

Incase this seems a bit complex here's a simplified version.
Step 1: Run `git branch budget-app` from `dev`. Creates new feature branch `budget-app`.
Step 2: Run `git rev-list --all --count`. Counts number of commits on dev branch.
Step 3: Run `git log -n {number of commits} --pretty=oneline` and copy the commit ID of the commit message at the very bottom of the list.
Step 3: Run `git reset --hard {commit ID}`. Resets all previous commits.
Step 4: Run `git push -f`. Forces new update on the branch.

That's it, you are done. It's that simple. Now all is left is for you to create a new pull request to merge the new feature branch to the dev again. The feature branch will still have your entire commit history.

<hr>

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
 
Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by jicamargo** [comment]
Thank you @KDlamini, now I understand. Thanks for your valuable solutions suggested!. I'll do it.

**Comment by jicamargo** [comment]
This PR was closed and replace by  a new one. (#6)

**Pull request closed without merging**
